#!/bin/bash
if [ "${name}x" == "x" ]
then
	echo "No mod name"
	exit 1
fi
if [ "${endble}x" = "x" ]
then
	enable=Yes
fi
temp=$(mktemp)
head -n -3 $fac/mods/mod-list.json >$temp
cat <<EOF >>$temp
    },
    {
EOF
echo '      "name": "'$name'",' >>$temp
if [[ "$enable" =~ ^(([Yy](es)?)|T(rue)?)$ ]]
then
	echo '      "enabled": true' >>$temp
else
	echo '      "enabled": false' >>$temp
fi
cat <<EOF >>$temp
    }
  ]
}
EOF
mv $temp $fac/mods/mod-list.json
