#!/bin/zsh
mkdir $fac/mods -p
while read type
do
  echo
  read name
  echo "reading $name"
  read url
  echo "url: $url"
  if [[ $type == 'git' ]]
  then
    echo -e "$name\n$url" | download.git
  elif [[ $type == 'file' ]]
  then
    echo -e "$name\n$url" | download.file
  fi
done
