#!/bin/bash
mkdir $fac/mods -p
while read type
do
	read url
	read name
	oldname=`ls $fac/mods/ -1 | grep -E "^${name}_"`
	echo $basename
	echo $url
	if [ $type == 'git' ]
	then
		if [ "${oldname}x" == "x" ]
		then
			if [ -d "${oldname}/.git" ]
			then
				rm -rf "${oldname}"
			fi
			git clone --depth 1 "https://github.com/$url.git" "$fac/mods/$name"
			cd "$fac/mods/$name"
			oldname="$name"
		else
			cd "$fac/mods/$oldname"
			git pull origin
		fi
		name="${name}_$(sed -n 's/^\s*"version": "\(.*\)",/\1/p' info.json)"
		if [ "$oldname" != "$name" ]
		then
			mv "$fac/mods/$oldname" \
				"$fac/mods/$name" -T
		fi
	elif [ $type == 'file' ]
	then
		name=`echo $url | cut -d/ -f 9`;
		if [ "${oldname}x" != "x" ]
		then
			if [ "$oldname" == "$name" ]
			then
				continue
			else
				rm -rf $fac/mods/$oldname
			fi
		fi
		curl --location --cookie "${cookie}" \
         --continue-at - "$url" -o "$fac/mods/$name"
	fi
done
