#!/bin/zsh
mkdir $fac/mods -p
while read type
do
  read name
  echo "reading $name"
  read url
  echo "url: $url"
  oldname=`ls $fac/mods/ -1 | grep -E "^${name}_"`
  if [[ $type == 'git' ]]
  then
    echo "Download by git"
    if [[ "${oldname}x" == "x" ]]
    then
      if [[ -d "${oldname}/.git" ]]
      then
        rm -rf "$fac/mods/$oldname"
      fi
      echo "clone"
      git clone --depth 1 "https://github.com/$url.git" "$fac/mods/$name" || exit $?
      cd "$fac/mods/$name"
      oldname="$name"
    else
      cd "$fac/mods/$oldname"
      echo "pull"
      git pull origin
    fi
    version="$(sed -rn 's/^\s*"version":\s*"(.*)"\s*,\s*$/\1/p' info.json)"
    if [[ ! $version =~ ^([0-9]+.)*[0-9]+$ ]]
    then
      echo "Cannot find mod version, add into nongit"
      echo "$name" >>$conf/nongit
      rerun=1
      rm -rf "$fac/mods/$oldname"
      continue
    fi
    name="${name}_${version}"
    if [[ "$oldname" != "$name" ]]
    then
      mv "$fac/mods/$oldname" \
        "$fac/mods/$name" -Tv
    fi
  elif [[ $type == 'file' ]]
  then
    echo "Download by file"
    name=`echo $url | cut -d/ -f 9`;
    if [[ "${oldname}x" != "x" ]]
    then
      if [[ "$oldname" == "$name" ]]
      then
        echo "Already new"
        continue
      else
        rm -rf $fac/mods/$oldname
      fi
    fi
    echo "Downloading"
    curl --location --cookie "${cookie}" \
      --continue-at - "$url" -o "$fac/mods/$name"
  fi
done
if [[ $rerun == 1 ]]
then
  >&2 echo -e '\033[31mPlaese re-run\033[0m'
fi
