#!/bin/zsh -e
read "new?Init a new config repository?[Y/n]"
if [[ "$new" =~ ^(([Yy](es)?)|)$ ]]
then
	echo "init a new"
	mkdir -p $conf
	cd $conf
	git init
	git commit -m "init" --allow-empty
	read "url?Input git URL:"
	git remote add origin "$url"
	git push --set-upstream origin master
	cp -r $fac/config/ $conf
	cp $fac/mods/mod-settings.json $conf
	sed -n 's/^\s*"name": "\(.*\)",$/\1: true/p' $fac/mods/mod-list.json | sort >$conf/modlist.yml
	push
	create_modlist <$conf/modlist.yml >$fac/mods/mod-list.json
else
	read "url?Input git URL"
	git clone $url $conf
	pull
fi
