#!/bin/zsh
if [ $# != 1 ] ; then
	read "new?Init a new config repository?[Y/n]"
	if [[ "$new" =~ ^(([Yy]|[Yy]es)|)$ ]]
	then
		echo "init a new"
		mkdir -p $conf
		cd $conf
		git init
		git commit -m "init" --allow-empty
		read "url?Input git URL:"
		git remote add origin "$url"
		git push --set-upstream origin master
		cp -r $fac/config/ $conf
		cp $fac/mods/mod-settings.json $conf
		cp $fac/mods/mod-list.json $conf
		push
		cache
	else
		read "url?Input git URL"
		git clone $url $conf
		pull
		cache
	fi
fi
