#!/bin/zsh -e
cp -r $fac/config/ $conf
cp $fac/mods/mod-settings.json $conf
cd $conf
read "message?Type message?[Y/n]"
if [[ "$message" =~ ^(([Yy]|[Yy]es)|)$ ]]
then
	read "message?Message: "
else
	message=`date --iso-8601`
fi
git add .
git commit -m "$message"
git push origin
