#!/bin/zsh -e

export cookie="$cache/cookie"
passwd
read "version?factorio version: "
download-info $version <$conf/modlist.yml 3<$conf/nongit | download
create_modlist <$conf/modlist.yml >$fac/mods/mod-list.json
